name: Metrics
on:
  schedule: # Ejecuta cada 24h
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecuci√≥n manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ferogv
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
